### ISSUE TITLE
A question: which file to use for DROPA analysis after peak calling

### ISSUE THREAD

**Issue by TakacsBertalan** [marcrusso/DROPA#2]
This isn't an issue whit DROPA but rather a question about best practices. I am new to DRIP-seq analysis, so sorry if this question sounds dumb!
I am using MACS2 for peak calling with the "-broad" option and I get three files as outputs: broadPeak, gappedPeak and peak.xlsx. I am not sure which file should I use for DROPA analysis, what is the correct practice?

**Comment by marcrusso** [comment]
Dear Bertalan, 
gappedPeak and broadPeak are both BED files so they should work with DROPA in any case.
Since you used MACS with the -broad flag, that is a good practice in DRIP-seq analysis, the broadPeak file is the dataset that you should use for downstream analysis.
I hope I have answered your question.

Marco

**Comment by TakacsBertalan** [comment]
Thank you for your fast reply and your help!
