### ISSUE TITLE
Using TPM values gives ValueError

### ISSUE THREAD

**Issue by TakacsBertalan** [marcrusso/DROPA#3]
Hi!
I have a problem with integrating tpm values into the DROPA analysis. I am analyzing mouse transcriptome and DRIP-seq data, using the mm10 genome as reference. My original file with the RPKM values looks like this:
```
ID	geneLength	allCountsMulti	filteredCountsMulti	dupRateMulti	dupsPerIdMulti	RPKMulti	RPKMMulti	allCounts	filteredCounts	dupRate	dupsPerId	RPK	RPKM
1	Gm26206	110	0	0	NA	0	0	0	0	0	NA	0	0	0
2	Xkr4	13657	0	0	NA	0	0	0	0	0	NA	0	0	0
3	Rp1	13415	0	0	NA	0	0	0	0	0	NA	0	0	0
4	Sox17	5720	27	26	0.037037037037037	1	4.72027972027972	0.134488953890936	27	26	0.037037037037037	1	4.72027972027972	0.134488953890936
5	Gm22307	107	0	0	NA	0	0	0	0	0	NA	0	0	0
6	Gm37323	2328	0	0	NA	0	0	0	0	0	NA	0	0	0
7	Gm39586	602	0	0	NA	0	0	0	0	0	NA	0	0	0
8	Gm46082	1551	0	0	NA	0	0	0	0	0	NA	0	0	0
9	Gm29874	3138	0	0	NA	0	0	0	0	0	NA	0	0	0
```
After calculating the TPM from the RPKM values and replacing the gene_id with transcript ID, my expression file looks like this:
```
Gene_ID    FPKM
XR_003949180.1	0.0
XM_011238395.3	0.0
NM_011283.2	0.0
XM_006495474.2	0.548112330999336
XR_003949345.1	0.0
XR_003947660.1	0.0
XR_003947708.1	0.0
XR_001778820.2	0.0
XR_001778819.2	0.0
```
I am running DROPA with the following command:
`sudo python3 ./DROPA/DROPA_v1.0.0.py -ref ./DROPA/GeneReference/mm10_RefSeq/ -o LiverDRIP_test -ex mouse_transcript_translated_tpm ./LiverDRIP_peaks_chrom.broadPeak`
And I am getting the
 ```
maxfpkm = max(fpkm)
ValueError: max() arg is an empty sequence
```
error message, which was addressed in another issue (https://github.com/marcrusso/DROPA/issues/1), but I use the mm10 mouse genome for both the transcriptome and DRIP-seq, so I don't believe that the solution there applies here.
Without the -ex option, the analysis completes without problems. What can I do to solve this? I am convinced that there is an error in my formatting or in the id's, but I can't figure it out
Thanks!

**Comment by marcrusso** [comment]
Dear Bertalan, 
I think there may be two things you can test:
1) your gene reference has a different version than the one used by DROPA, so you can create a custom dataset following this guide (https://github.com/marcrusso/DROPA/wiki/Custom-Gene-Reference)
2) you said you "replaced" gene_id with transcript_id. If you did this "creating" transcripts with the same TPM value of the gene, this is incorrect from the "biological" point of view (you can collapse different transcripts expression to overall gene expression, but not viceversa) Probably the error is due to the fact that for different transcripts (related to the same gene) you have the exact TPM level. You shoud try to quantify again your RNAseq data using transcript_id as reference. 

Let me know if it works!

Marco

**Comment by TakacsBertalan** [comment]
Dear Marco! Thank you for your help, both of your advices were helpful and I could solve the problem!
Thanks,
Bertalan Takacs

**Comment by marcrusso** [comment]
You're welcome!

Marco
