### ISSUE TITLE
Change time.clock() in DROPAcore.py file

### ISSUE THREAD

**Issue by SamGallaher** [marcrusso/DROPA#4]
time.clock() in line 100, 232, 432 and 460 results in an error in DROPAcore.py - fixed by changing time.clock() to time.process_time()

OS: Ubuntu 20.04
Python 3.9.7

**Comment by marcrusso** [comment]
Thank you!
I noticed this bug since time.clock() function is deprecated in newer version of python. 
We will fix this issue soon and add some other features to DROPA.
I added a conda environment (DROPA.yml) that will allow you to use DROPA until we'll release the new version.
Thank you again for your help and for using DROPA!! 

Marco
